#!/bin/sh
# File generated by ocamlbuild

cd /Users/jd/Desktop/S21/3110/CamelQuest/_build/default

rm -f .main.eobjs/byte/dune__exe.cmi
rm -f .main.eobjs/byte/dune__exe.cmo
rm -f .main.eobjs/byte/dune__exe__Dungeon.cmi
rm -f .main.eobjs/byte/dune__exe__Dungeon.cmo
rm -f .main.eobjs/byte/dune__exe__Main.cmi
rm -f .main.eobjs/byte/dune__exe__Main.cmo
rm -f .main.eobjs/byte/dune__exe__State.cmi
rm -f .main.eobjs/byte/dune__exe__State.cmo
rm -f .main.eobjs/byte/dune__exe__Texturemap.cmi
rm -f .main.eobjs/byte/dune__exe__Texturemap.cmo
rm -f .main.eobjs/native/dune__exe.cmx
rm -f .main.eobjs/native/dune__exe.o
rm -f .main.eobjs/native/dune__exe__Dungeon.cmx
rm -f .main.eobjs/native/dune__exe__Dungeon.o
rm -f .main.eobjs/native/dune__exe__Main.cmx
rm -f .main.eobjs/native/dune__exe__Main.o
rm -f .main.eobjs/native/dune__exe__State.cmx
rm -f .main.eobjs/native/dune__exe__State.o
rm -f .main.eobjs/native/dune__exe__Texturemap.cmx
rm -f .main.eobjs/native/dune__exe__Texturemap.o
# Also clean the script itself
rm -f /Users/jd/Desktop/S21/3110/CamelQuest/_build/default/_build/sanitize.sh
